print ('Digite 2 numeros inteiros e um numero real')
ni1 = float(input('1º Numero inteiro : '))
ni2 = float(input('2° Numero inteiro : '))
nr = float(input('Numero real : '))
print()
respa = (ni1*2)*(ni2/2)
print('O produto do dobro do primeiro com metade do segundo : %.2f' %respa)
print()
respb = (ni1*3)+(nr)
print('A soma do triplo do primeiro com o terceiro : %.2f' %respb)
print()
respc = nr**2
print('O terceiro elevado ao cubo : %.2f' %respc)